<a href="https://colab.research.google.com/github/HRIDYANS/MY_PYTHON_PROJECT/blob/main/Project_3_Num_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. **Create an array of numbers from 1 to 20 and reshape it into a 4×5 matrix**

In [1]:

import numpy as np

arr = np.arange(1, 21).reshape(4, 5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**2. Create an array of 10 zeros and replace the 5th element with 100**

In [2]:

arr = np.zeros(10, dtype=int)
arr[4] = 100
print(arr)


[  0   0   0   0 100   0   0   0   0   0]


**3. Create a NumPy array of even numbers between 2 and 40**

In [ ]:
arr = np.arange(2, 41, 2)

**4.Generate a 1D array of 15 random integers between 1 and 100 and find its min, max, mean, and standard deviation**

In [3]:

arr = np.random.randint(1, 101, 15)
print("Array:", arr)
print("Min:", arr.min())
print("Max:", arr.max())
print("Mean:", arr.mean())


Array: [10 46 42  8 21 99 44 44 63 14 18 36 65 89 60]
Min: 8
Max: 99
Mean: 43.93333333333333


**5. Given two arrays of sales and costs, calculate profit and profit percentage arrays**

In [4]:

sales = np.array([200, 300, 400, 500])
costs = np.array([150, 200, 250, 300])

profit = sales - costs
profit_percentage = (profit / sales) * 100

print("Profit:", profit)
print("Profit %:", profit_percentage)


Profit: [ 50 100 150 200]
Profit %: [25.         33.33333333 37.5        40.        ]


**6. Create a 6×6 random matrix and compute row sums, column sums, and total sum**

In [5]:

matrix = np.random.randint(1, 100, (6, 6))
row_sums = matrix.sum(axis=1)
col_sums = matrix.sum(axis=0)
total_sum = matrix.sum()

print("Matrix:\n", matrix)
print("Row sums:", row_sums)
print("Column sums:", col_sums)
print("Total sum:", total_sum)


Matrix:
 [[63 44 79 82 92  3]
 [87 35 15 32 57 94]
 [53 86 35 69 22 76]
 [73 89 30 53 26 92]
 [59 86 21 88 88 15]
 [63 41 24 39 75 89]]
Row sums: [363 320 341 363 357 331]
Column sums: [398 381 204 363 360 369]
Total sum: 2075


**7. Given stock prices, compute daily returns using vectorized NumPy operations**

In [6]:

prices = np.array([100, 102, 101, 105, 110])
returns = (prices[1:] - prices[:-1]) / prices[:-1]

print("Daily Returns:", returns)


Daily Returns: [ 0.02       -0.00980392  0.03960396  0.04761905]


**8. Convert an array of annual interest rates into monthly rates using vectorization**

In [7]:

annual_rates = np.array([0.06, 0.08, 0.10])
monthly_rates = annual_rates / 12

print("Monthly Rates:", monthly_rates)


Monthly Rates: [0.005      0.00666667 0.00833333]


**9. Normalize a given array of portfolio weights so that the sum becomes 1**

In [8]:

weights = np.array([0.2, 0.3, 0.4, 0.5])
normalized_weights = weights / weights.sum()

print("Normalized Weights:", normalized_weights)


Normalized Weights: [0.14285714 0.21428571 0.28571429 0.35714286]


**10. Create a Pandas Series and find mean, max, and index of max value**

In [9]:

import pandas as pd

data = [1200, 1500, 1800, 2000, 2200]
series = pd.Series(data)

print("Mean:", series.mean())
print("Max:", series.max())
print("Index of Max:", series.idxmax())


Mean: 1740.0
Max: 2200
Index of Max: 4


**11. Create a DataFrame with Student Name + 3 subject marks**

In [10]:

import pandas as pd

# Create DataFrame
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [85, 90, 78],
    "Science": [88, 76, 92],
    "English": [80, 85, 89]
})

# Print only Math column
print(df["Math"])

# Print first 2 rows
print(df.head(2))

# Print shape
print("Shape:", df.shape)


0    85
1    90
2    78
Name: Math, dtype: int64
    Name  Math  Science  English
0  Alice    85       88       80
1    Bob    90       76       85
Shape: (3, 4)


**12. Filter rows based on Balance**

In [11]:

import pandas as pd

df = pd.DataFrame({
    "Account": [101, 102, 103, 104],
    "Balance": [5000, 15000, 7000, 12000]
})

print(df[df["Balance"] > 8000])


   Account  Balance
1      102    15000
3      104    12000
